<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- ORM (Entity Framework Core) - позволяет работать с базой данных при помощи объектов -->
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <!-- Расширение для конфигурирования моделей и создания миграций -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <!-- Провайдер Entity Framework Core для работы с PostgreSQL -->
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DirectoryService.UseCases\DirectoryService.UseCases.csproj" />
  </ItemGroup>

</Project>
