<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\Domain\Domain.csproj" />
  </ItemGroup>

  <!-- Задача 13: глобальный using для Result-паттерна. -->
  <ItemGroup>
    <Using Include="Domain.Common" />
    <Using Include="Domain.Common.Result" Static="true" />
  </ItemGroup>

</Project>
